# Generated by Django 3.2.4 on 2021-06-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAutomotora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anioFabricacion',
            field=models.IntegerField(),
        ),
    ]
