# Generated by Django 3.2.4 on 2021-06-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAutomotora', '0002_alter_vehiculo_aniofabricacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='anioFabricacion',
            new_name='añoFabricacion',
        ),
    ]
