# Generated by Django 3.2.4 on 2021-06-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAutomotora', '0003_rename_aniofabricacion_vehiculo_añofabricacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='añoFabricacion',
            new_name='año_Fabricacion',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='fechaRecepcion',
            new_name='fecha_Recepcion',
        ),
    ]
