# Generated by Django 3.2.4 on 2021-06-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAutomotora', '0004_auto_20210615_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='año_Fabricacion',
            new_name='año_Fabricación',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='fecha_Recepcion',
            new_name='fecha_Recepción',
        ),
    ]
